# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Steven Wolf
email: wolfs15@ecu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Thoughts and projects from Dr. Steven Wolf, Assistant Professor of Physics at
  East Carolina University. Posted work is licensed under a Creative Commons
  BY-NC-SA 4.0 License unless noted otherwise.

show_excerpts: false # set to true to show excerpts on the homepage

github_username:  sfwolfphys


# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude: ['*.Rmd']

ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

